PyPI does not duplicate link if the URL is named `Homepage`
moshez/pyproject-only-example pull request #1
Opened 2022-03-07 17:36 UTC by abravalheri

Hi @moshez, I was just experimenting and I found out that PyPI will not duplicate the `Homepage` URL if it is written exactly like that (no dash, first letter capital).

These are the experiments: https://test.pypi.org/project/orbipatch/

2022-03-07 21:09 UTC, moshez requested changes
Thank you for the update @abravalheri , this is great to know!

Do you mind at least fixing the typo? I'll be happy to merge it then.

2022-03-07 21:09 UTC, moshez commented on README.rst
> +PyPI from having it double liked,
Typo: `linked`

Probably better phrasing:

```
If you want to avoid
having it double-linked from PyPI
please use
:code:`Homepage`.
```

2022-03-07 22:30 UTC, abravalheri commented on README.rst
> +PyPI from having it double liked,
Done ;)

2022-03-08 14:20 UTC, moshez approved these changes

2022-03-08 14:20 UTC, merged